UAS_20170140141_RizkiFajar/Controllers/KamarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UAS_20170140141_RizkiFajar.Models;

namespace UAS_20170140141_RizkiFajar.Controllers
{
    public class KamarController : Controller
    {
        private readonly UASPAWContext _context;

        public KamarController(UASPAWContext context)
        {
            _context = context;
        }

        // GET: Kamar
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kamar.ToListAsync());
        }

        // GET: Kamar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kamar = await _context.Kamar
                .FirstOrDefaultAsync(m => m.IdKamar == id);
            if (kamar == null)
            {
                return NotFound();
            }

            return View(kamar);
        }

        // GET: Kamar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kamar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKamar,TypeKamar,NoKamar,Lantai,Biaya,Status")] Kamar kamar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kamar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kamar);
        }

        // GET: Kamar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kamar = await _context.Kamar.FindAsync(id);
            if (kamar == null)
            {
                return NotFound();
            }
            return View(kamar);
        }

        // POST: Kamar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKamar,TypeKamar,NoKamar,Lantai,Biaya,Status")] Kamar kamar)
        {
            if (id != kamar.IdKamar)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kamar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KamarExists(kamar.IdKamar))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kamar);
        }

        // GET: Kamar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kamar = await _context.Kamar
                .FirstOrDefaultAsync(m => m.IdKamar == id);
            if (kamar == null)
            {
                return NotFound();
            }

            return View(kamar);
        }

        // POST: Kamar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kamar = await _context.Kamar.FindAsync(id);
            _context.Kamar.Remove(kamar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KamarExists(int id)
        {
            return _context.Kamar.Any(e => e.IdKamar == id);
        }
    }
}

UAS_20170140141_RizkiFajar/Controllers/MakananController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UAS_20170140141_RizkiFajar.Models;

namespace UAS_20170140141_RizkiFajar.Controllers
{
    public class MakananController : Controller
    {
        private readonly UASPAWContext _context;

        public MakananController(UASPAWContext context)
        {
            _context = context;
        }

        // GET: Makanan
        public async Task<IActionResult> Index()
        {
            return View(await _context.Makanan.ToListAsync());
        }

        // GET: Makanan/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var makanan = await _context.Makanan
                .FirstOrDefaultAsync(m => m.IdMakanan == id);
            if (makanan == null)
            {
                return NotFound();
            }

            return View(makanan);
        }

        // GET: Makanan/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Makanan/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMakanan,PaketMakanan,HargaPermakanan")] Makanan makanan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(makanan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(makanan);
        }

        // GET: Makanan/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var makanan = await _context.Makanan.FindAsync(id);
            if (makanan == null)
            {
                return NotFound();
            }
            return View(makanan);
        }

        // POST: Makanan/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMakanan,PaketMakanan,HargaPermakanan")] Makanan makanan)
        {
            if (id != makanan.IdMakanan)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(makanan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MakananExists(makanan.IdMakanan))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(makanan);
        }

        // GET: Makanan/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var makanan = await _context.Makanan
                .FirstOrDefaultAsync(m => m.IdMakanan == id);
            if (makanan == null)
            {
                return NotFound();
            }

            return View(makanan);
        }

        // POST: Makanan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var makanan = await _context.Makanan.FindAsync(id);
            _context.Makanan.Remove(makanan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MakananExists(int id)
        {
            return _context.Makanan.Any(e => e.IdMakanan == id);
        }
    }
}

UAS_20170140141_RizkiFajar/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;

namespace UAS_20170140141_RizkiFajar.Controllers
{
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;
        // Injecting Role Manager
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

UAS_20170140141_RizkiFajar/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using _20170140141_RizkiFajar_UCp1.Models.Upload;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;

namespace UAS_20170140141_RizkiFajar.Controllers
{
    public class UploadController : Controller
    {
        
            private readonly IFileProvider fileProvider;
            public UploadController(IFileProvider fileProvider)
            {
                this.fileProvider = fileProvider;
            }
            public IActionResult Index()
            {
                return View();
            }
            [HttpPost]
            public async Task<IActionResult> UploadFile(IFormFile file)
            {
                if (file == null || file.Length == 0)
                    return Content("file not selected");

                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/Upload",
                            file.GetFilename());

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                return RedirectToAction("Files");
            }

            [HttpPost]
            public async Task<IActionResult> UploadFiles(List<IFormFile> files)
            {
                if (files == null || files.Count == 0)
                    return Content("files not selected");

                foreach (var file in files)
                {
                    var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/Upload",
                            file.GetFilename());

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }

                return RedirectToAction("Files");
            }

            [HttpPost]
            public async Task<IActionResult> UploadFileViaModel(FileInputModel model)
            {
                if (model == null ||
                    model.FileToUpload == null || model.FileToUpload.Length == 0)
                    return Content("file not selected");

                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/Upload",
                            model.FileToUpload.GetFilename());

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await model.FileToUpload.CopyToAsync(stream);
                }

                return RedirectToAction("Files");
            }

            public IActionResult Files()
            {
                var model = new FilesViewModel();
                foreach (var item in this.fileProvider.GetDirectoryContents(""))
                {
                    model.Files.Add(
                        new FileDetails { Name = item.Name, Path = item.PhysicalPath });
                }
                return View(model);
            }

            public async Task<IActionResult> Download(string filename)
            {
                if (filename == null)
                    return Content("filename not present");

                var path = Path.Combine(
                               Directory.GetCurrentDirectory(),
                               "wwwroot/Upload", filename);

                var memory = new MemoryStream();
                using (var stream = new FileStream(path, FileMode.Open))
                {
                    await stream.CopyToAsync(memory);
                }
                memory.Position = 0;
                return File(memory, GetContentType(path), Path.GetFileName(path));
            }

            private string GetContentType(string path)
            {
                var types = GetMimeTypes();
                var ext = Path.GetExtension(path).ToLowerInvariant();
                return types[ext];
            }

            private Dictionary<string, string> GetMimeTypes()
            {
                return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
            }
            //public IActionResult Index()
            //{
            //    return View();
            //}
    }
}

UAS_20170140141_RizkiFajar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UAS_20170140141_RizkiFajar</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">UAS_20170140141_RF</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Upload" asp-action="Index">Upload</a></li>
                    <li><a asp-area="" asp-controller="Role" asp-action="Index">Role</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daftar adm<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Reservasi" asp-action="Index">Reservasi</a></li>
                            <li><a asp-area="" asp-controller="Kamar" asp-action="Index">Kamar</a></li>

                        </ul>
                    </li>
                    }
                    else if (User.IsInRole("Resepsionis"))
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daftar Reseps<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Reservasi" asp-action="Index">Reservasi</a></li>
                            <li><a asp-area="" asp-controller="Kamar" asp-action="Index">Kamar</a></li>
                        </ul>
                    </li>
                    }
                    else if (User.IsInRole("Cleaning Service"))
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daftar cleaning<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="RoomService" asp-action="Index">RoomService</a></li>
                        </ul>
                    </li>
                    }
                    else if (User.IsInRole("Kitchen"))
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daftar kitchen<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Makanan" asp-action="Index">Makanan</a></li>
                        </ul>
                    </li>
                    }

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - UAS_20170140141_RizkiFajar</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

UAS_20170140141_RizkiFajar/Views/Shared/_LayoutDashio.cshtml
@{
    ViewData["Title"] = "_LayoutDashio";
}

<h2>_LayoutDashio</h2>